# Generated by Django 6.0.4 on 2026-04-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('route', 'Route dégradée'), ('inondation', 'Inondation'), ('accident', 'Accident'), ('eclairage', 'Éclairage défaillant'), ('dechet', 'Déchets'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/')),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='signale', max_length=20)),
                ('priorite', models.CharField(choices=[('vert', 'Vert - Faible'), ('orange', 'Orange - Moyen'), ('rouge', 'Rouge - Urgent')], default='vert', max_length=10)),
                ('importance', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Peu important'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Très important')], help_text='Degré d’importance défini par une autorité (1-5)', null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('confirmation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut'], name='incidents_i_statut_1c2beb_idx'), models.Index(fields=['type'], name='incidents_i_type_2c1cd5_idx'), models.Index(fields=['priorite'], name='incidents_i_priorit_3074a2_idx')],
            },
        ),
    ]
